global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: issue-tracker-service-cloud-run
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets:
          - issue-tracker-service-688420327904.us-central1.run.app

  - job_name: issue-tracker-service-local
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8000
